---
Name: socialfeed
---
# job frequency feed
SilverstripeSocialFeed\Jobs\SocialFeedCacheQueuedJob:
  time_offset: 900
# cache lifetime for a feed
SilverstripeSocialFeed\Provider\SocialFeedProvider:
  default_cache_lifetime: 1800
# cache backend
SilverStripe\Core\Injector\Injector:
  Psr\SimpleCache\CacheInterface.socialfeedcache:
    factory: SilverStripe\Core\Cache\CacheFactory
    constructor:
      namespace: 'socialfeedcache'
# CMS extensions, if installed
---
Only:
  moduleexists: 'silverstripe/cms'
---
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    -  SilverstripeSocialFeed\Extensions\SocialFeedControllerExtension
